# python and sudo are required for closure linter:
# `sudo python setup.py install`

sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script: ./runtest
notifications:
  email:
    recipients: dev@dtm.io
